import Utilities.Code;

import java.util.HashMap;
import java.util.Objects;

public class Shelf {

    public static final int SHELF_NUMBER_ = 0;
    public static final int SUBJECT_ = 1;

    private int shelfNumber;
    private String subject;
    private HashMap<Book, Integer> books;

    public Shelf(int shelfNumber, String subject) {
        this.shelfNumber = shelfNumber;
        this.subject = subject;

        this.books = new HashMap<>(); // initializing the hashmap
    }

    // generated by intellij, made sure it only involves subject and shelfNumber

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Shelf shelf = (Shelf) o;
        return shelfNumber == shelf.shelfNumber && Objects.equals(subject, shelf.subject);
    }

    @Override
    public int hashCode() {
        return Objects.hash(shelfNumber, subject);
    }

    @Override
    public String toString() {
        return shelfNumber + " : " + subject;
    }

    public int getBookCount(Book book) {
        if (!books.containsKey(book)) {
            return -1;
        }

        return books.get(book);
    }

    public Code addBook(Book book) { // oh my god not another Code type
        if (!book.getSubject().equals(subject)) {
            return Code.SHELF_SUBJECT_MISMATCH_ERROR;
        }

        if (books.containsKey(book)) {
            books.put(book, books.get(book) + 1);
        }
        else {
            books.put(book, 1);
        }

        System.out.println(book + " added to shelf " + this);
        return Code.SUCCESS;
    }

    public Code removeBook(Book book) {
        int count = books.get(book);

        if (!books.containsKey(book)) {
            System.out.println(book.getTitle() + " is not on shelf " + subject);
            return Code.BOOK_NOT_IN_INVENTORY_ERROR;
        }

        if (count == 0) {
            System.out.println("No copies of " + book.getTitle() + " remain on shelf " + subject);
            return Code.BOOK_NOT_IN_INVENTORY_ERROR;
        }

        books.put(book, count- 1);
        System.out.println(book.getTitle() + " removed from shelf " + subject);
        return Code.SUCCESS;
    }

    public String listBooks() {
        StringBuffer sb = new StringBuffer();

        int total = 0;
        for (int count : books.values()) {
            total += count;
        }

        if (total == 1) {
            sb.append(" book on shelf: ");
        }
        else {
            sb.append(" books on shelf: ");
        }
        sb.append("\n"); // new line!

        for (Book current : books.keySet()) {
            sb.append(current).append(" ").append(books.get(current)).append("\n");
        }

        return sb.toString();
    }

}
