import Utilities.Code;

import java.util.HashMap;
import java.util.Objects;

public class Shelf {

    public static final int SHELF_NUMBER_ = 0;
    public static final int SUBJECT_ = 1;

    private int shelfNumber;
    private String subject;
    private HashMap<Book, Integer> books;

    public Shelf(int shelfNumber, String subject) {
        this.shelfNumber = shelfNumber;
        this.subject = subject;

        this.books = new HashMap<>(); // initializing the hashmap
    }

    // generated by intellij, made sure it only involves subject and shelfNumber

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Shelf shelf = (Shelf) o;
        return shelfNumber == shelf.shelfNumber && Objects.equals(subject, shelf.subject);
    }

    @Override
    public int hashCode() {
        return Objects.hash(shelfNumber, subject);
    }

    @Override
    public String toString() {
        return shelfNumber + " : " + subject;
    }

    public int getBookCount(Book book) {
        if (!books.containsKey(book)) {
            return -1;
        }

        return books.get(book);
    }

    public Code addBook(Book book) { // oh my god not another Code type

    }

}
