import Utilities.Code;

import java.util.HashMap;
import java.util.Objects;

/**
 * @author Josue Nava - Jimenez
 * Shelf.java is a nice little file that stores books of a specific subject (like an actual shelf, wow!)
 * (also tracks the number of copies of each book btw)
 */

public class Shelf {

    public static final int SHELF_NUMBER_ = 0;
    public static final int SUBJECT_ = 1;

    private int shelfNumber;
    private String subject;
    private HashMap<Book, Integer> books;

    /**
     * basic constructor, initializes the book's shelf number & subject, as well as the books HashMap
     */
    public Shelf(int shelfNumber, String subject) {
        this.shelfNumber = shelfNumber;
        this.subject = subject;

        this.books = new HashMap<>(); // initializing the hashmap
    }

    /**
     * even simpler constructor, only initializes the books HashMap
     */
    public Shelf() {
        this.books = new HashMap<>(); // uh... grab a nice small latte or something
    }

    /**
     * returns the shelf number
     */
    public int getShelfNumber() {
        return shelfNumber;
    }

    /**
     * sets the shelf number
     */
    public void setShelfNumber(int shelfNumber) {
        this.shelfNumber = shelfNumber;
    }

    /**
     * returns subject
     */
    public String getSubject() {
        return subject;
    }

    /**
     * sets subject
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * returns books HashMap
     */
    public HashMap<Book, Integer> getBooks() {
        return books;
    }

    /**
     * sets books HashMap
     */
    public void setBooks(HashMap<Book, Integer> books) {
        this.books = books;
    }

    // generated by intellij, made sure it only involves subject and shelfNumber
    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Shelf shelf = (Shelf) o;
        return shelfNumber == shelf.shelfNumber && Objects.equals(subject, shelf.subject);
    }

    // same deal
    @Override
    public int hashCode() {
        return Objects.hash(shelfNumber, subject);
    }

    /**
     * prints string representation of a book's shelf number and subject
     */
    @Override
    public String toString() {
        return shelfNumber + " : " + subject;
    }

    /**
     * returns number of books in a specific shelf
     */
    public int getBookCount(Book book) {
        if (!books.containsKey(book)) {
            return -1;
        }

        return books.get(book);
    }

    /**
     * adds book to a specific shelf
     */
    public Code addBook(Book book) { // oh my god not another Code type
        if (!book.getSubject().equals(subject)) {
            return Code.SHELF_SUBJECT_MISMATCH_ERROR;
        }

        if (books.containsKey(book)) {
            books.put(book, books.get(book) + 1);
        }
        else {
            books.put(book, 1);
        }

        System.out.println(book + " added to shelf " + this);
        return Code.SUCCESS;
    }

    /**
     * removes book from a specific shelf
     */
    public Code removeBook(Book book) {
        if (!books.containsKey(book)) {
            System.out.println(book.getTitle() + " is not on shelf " + subject);
            return Code.BOOK_NOT_IN_INVENTORY_ERROR;
        }

        int count = books.get(book); // moved it here to fix test issues

        if (count == 0) {
            System.out.println("No copies of " + book.getTitle() + " remain on shelf " + subject);
            return Code.BOOK_NOT_IN_INVENTORY_ERROR;
        }

        books.put(book, count- 1);
        System.out.println(book.getTitle() + " removed from shelf " + subject);
        return Code.SUCCESS;
    }

    /**
     * lists all books in a specific shelf
     */
    public String listBooks() {
        StringBuffer sb = new StringBuffer();

        int total = 0;
        for (int count : books.values()) {
            total += count;
        }

        // update: appending 'this' fixed the last test failure
        if (total == 1) {
            sb.append(total).append(" book on shelf: ").append(this).append("\n");
        }
        else {
            sb.append(total).append(" books on shelf: ").append(this).append("\n");
        }

        for (Book current : books.keySet()) {
            sb.append(current).append(" ").append(books.get(current)).append("\n");
        }

        return sb.toString();
    }

}
